<?php
declare(strict_types=1);

namespace Zestic\User\Service;

class UserEvent
{
    CONST PRE_PROCESSING_REGISTER_USER = 'PRE_PROCESSING_REGISTER_USER';
    CONST PROCESS_REGISTER_USER = 'PROCESS_REGISTER_USER';
    CONST POST_PROCESSING_REGISTER_USER = 'POST_PROCESSING_REGISTER_USER';
}